Change to check build status

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -24,9 +24,10 @@
 #    and best practices on handling the access key credentials.
 
 on:
-  release:
-    types: [created]
-
+  push:
+    branches:
+      - master
+        - 
 name: Deploy to Amazon ECS
 
 jobs:
@@ -35,6 +36,22 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check commit status
+      id: commit-status
+      run: |
+          # Check the status of the Git commit
+          CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+          echo "Current status is: $CURRENT_STATUS"
+          while [ "${CURRENT_STATUS^^}" = "PENDING" ]; 
+            do sleep 10; 
+            CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+          done;
+          echo "Current status is: $CURRENT_STATUS"
+          if [ "${CURRENT_STATUS^^}" = "FAILURE" ]; 
+            then echo "Commit status failed. Canceling execution"; 
+            exit 1; 
+          fi
+
     - name: Checkout
       uses: actions/checkout@v2
 
